// apps/web/src/routes/internal/projects/search/+page.svelte
<script lang="ts">
	import { Paginator } from '@skeletonlabs/skeleton';
	import type { PaginationSettings } from '@skeletonlabs/skeleton';
	import type { PageData } from './$types';
	import Icon from '@iconify/svelte';
	import { enhance } from '$app/forms';
	export let data: PageData;

	let paginationSettings: PaginationSettings = {
		page: 0,
		limit: 10,
		size: data.projects.length,
		amounts: [1, 2, 5, 10, 20]
	};

	let headers = ['ID', 'Name', 'Comercial Designation', 'Leader', 'Status', 'Type', 'Actions'];

	let paginatedSource: {
		id: number;
		status: string;
		name: string;
		comercialDesignation: string;
		leader: string;
        type: string;
	}[] = [];

	$: paginatedSource = data.projects.slice(
		paginationSettings.page * paginationSettings.limit,
		paginationSettings.page * paginationSettings.limit + paginationSettings.limit
	);

</script>

<main class="w-full">
	<h1 class="text-3xl font-bold text-center">Search Projects</h1>
    <form method="post" use:enhance class="grid grid-cols-3 gap-5 my-3 border-b p-3 pb-8 border-b-primary-400/30">
        <label for="id" class="label">
            <span>ID</span>
            <input type="text" class="input (text)" name="id" id="id">
        </label>
        <label for="name" class="label">
            <span>name</span>
            <input type="text" class="input (text)" name="name" id="name">
        </label>
        <label for="comercialDesignation" class="label">
            <span>Comercial Designation</span>
            <input type="text" class="input (text)" name="comercialDesignation" id="comercialDesignation">
        </label>
        <label for="leader" class="label">
            <span>Leader ID</span>
            <input type="number" class="input" id="leader" name="leaderId">
        </label>
        <label for="leader" class="label">
            <span>Type</span>
            <input type="text" class="input" id="leader" name="type">
        </label>
        <label for="status" class="label">
            <span>Status</span>
            <select id="status" name="status" class="select rounded-full">
                <option value="">All</option>
				<option value="Active">Active</option>
				<option value="Inactive">Inactive</option>
				<option value="Abandoned">Abandoned</option>
				<option value="Finished">Finished</option>
				<option value="Pending">Pending</option>
			</select>
        </label>
        <div class="col-span-3 w-full flex justify-center gap-x-4">
            <button type="reset" class="btn variant-filled-surface">Clean Filters</button>
            <button type="submit" class="btn variant-filled-primary">Search</button>
        </div>
    </form>
    <h2 class="text-2xl font-semibold">Projects List</h2>
	<table class="table !my-4">
        <tr>
            {#each headers as header}
                <th class="text-left !p-3">{header}</th>
            {/each}
        </tr>
        {#each paginatedSource as item}
            <tr>
                <td class="!p-3">{item.id}</td>
                <td class="!p-3">{item.name}</td>
                <td class="!p-3">{item.comercialDesignation}</td>
                <td class="!p-3">{item.leader}</td>
                <td class="!p-3">{item.status}</td>
                <td class="!p-3">{item.type}</td>
                <td class="!p-3">
                    <a href="/internal/projects/search" class="btn btn-icon variant-ghost-primary">
                        <Icon icon="mdi:eye-outline" class="h-"/>
                    </a>
                </td>
            </tr>
        {/each}
    </table>
	<Paginator
		bind:settings={paginationSettings}
		showFirstLastButtons={false}
		showPreviousNextButtons={true}
	/>
</main>

// apps/web/pages/internal/projects/search/index.tsx
import { Combobox } from '@/components/Combobox';
import { Nav } from '@/components/Nav'
import { SelectInput } from '@/components/Select';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input'
import { client } from '@/lib/axios';
import { Employee, Project } from '@/lib/types';
import { NextPage, GetServerSideProps } from 'next'
import * as z from "zod"
import { DataTable } from './data-table';
import { columns } from './columns';

interface Props {
  employees: { label: string, value: number }[],
  projects: Project[]
}

const stateOptions = [
  { label: "Active", value: "Active" },
  { label: "Inactive", value: "Inactive" },
  { label: "Pending", value: "Pending" },
  { label: "Finished", value: "Finished" },
  { label: "Abandoned", value: "Abandoned" },
];

function Index({employees, projects}: Props) {
  return (
    <>
      <Nav />
      <section className="h-screenav">
        <h2 className="text-3xl font-semibold text-center py-3">
          Search projects
        </h2>
        <div className="mx-auto pb-16 pt-4 max-w-[85vw]">
          <form className="max-w-[70vw] mx-auto flex flex-wrap w-full place-content-center">
            <span className="w-1/3 p-4">
              <label htmlFor="id">Project ID</label>
              <Input name="id" />
            </span>
            <span className="w-1/3 p-4">
              <label htmlFor="name">Project Name</label>
              <Input name="name" />
            </span>
            <span className="w-1/3 p-4">
              <label htmlFor="comercialDesignation">
                Commercial Designation
              </label>
              <Input name="comercialDesignation" />
            </span>
            <span className="w-1/3 p-4">
              <label htmlFor="status">Project Status</label>
              <SelectInput
                data={stateOptions}
                label="Select a status"
                placeholder=""
                className="!w-full"
              />
            </span>
            <span className="w-1/3 p-4 flex flex-col">
              <label htmlFor="leader">Leader</label>
              <Combobox
                data={employees}
                label="Search a leader"
                placeholder="Leader..."
                className="w-full"
              />
            </span>
            <span className="w-1/3 p-4">
              <label htmlFor="type">Project Type</label>
              <Input name="type" />
            </span>
            <div className='my-4 flex flex-col md:flex-row gap-4'>
              <Button variant={'secondary'}>Clear filters</Button>
              <Button variant={'default'} >Search</Button>
            </div>
          </form>
          <div className="mx-auto w-[80vw] my-4">
          <DataTable columns={columns} data={projects}/>
          </div>
        </div>
      </section>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  try {
    const { data }: { data: Employee[] } = await client.get("/api/employees");
    console.log(data);

    const employees = data.map((item) => ({
      label: `${item.name} ${item.lastName}`,
      value: item.id,
    }));

    const { data: projects }: { data: Project[] } = await client.get("/api/projects")
    return {
      props: {
        employees: employees,
        projects: projects
      },
    };
  } catch (e) {
    return {
      props: {
        employees: [],
      },
    };
  }
}

export default Index
